### ISSUE TITLE
NEXT?

### ISSUE THREAD

**Issue by jimrothstein** [JosiahParry/opensecrets#10]
Dark Money -- Jane Mayer is terrific  & will look at book.

Here's my 2 cents, possible way we might proceed:

1.  I'd like to **finish simple test code for each FUN in pkg,** such as started here (a mess right now)  [testing_opensecrets](https://github.com/jimrothstein/testing_opensecrets/blob/master/rmd/0001_api.Rmd).

2.  Possible using pkg **testthat** (let me see before commit to it).

3.  Once I am here, maybe we could talk more about documentation and direction.   Of course, it would be nice to add or supplement work being done by active campaign watchdogs.

4.  fyi, did a quick Github search for "opensecrets", but did find much in way of current development or analysis (is it all done by newspapers & publications??)

OK on 1, above?

**Comment by JosiahParry** [comment]
Hey Jim! 

I have no ideas for what to continue doing here. Their API is very weak and one thing I'd like to do is submit a number of feature requests to OS so that they can improve their public facing API. My suspicion is that they do not know it is being used. Additionally, the R based API wrapper that they point to on their website is very outdated. Perhaps we can get this package on there as a replacement?

Additionally, it would be very awesome if you can create some degree of testing coverage using testthat.

**Comment by jimrothstein** [comment]
Will start on **testthat** code.

fyi, 

Here is code for Fuller's **ropensecretsapi** package:
* https://bitbucket.org/CoherentLogic/r-open-secrets-api/src/master/R/ropensecretsapi.R.
*  Built upon [RCurl](https://cran.r-project.org/web/packages/RCurl/)

Whereas your **opensecrets** package:
*  Built upon **httr**,  which in turn uses this [r package Curl](https://cran.r-project.org/web/packages/curl/vignettes/intro.html)

Of course, both are based on **libcurl**

First glance at Fuller's code,though, is there seems to be nice function structure to it, even if much older.

BTW,  what is best way to contact you?

**Comment by JosiahParry** [comment]
the initial iteration of it is from 2014 and hasn't been updated since then! I think we're in a better and more useable pattern right now. 

The best way to communicate is probably via GH issue so we can have convos related to issues. Alternatively reach me at josiah.parry@gmail.com
